### ISSUE TITLE
Highlight current mission/job needs

### ISSUE THREAD

**Issue by steveklabnik** [MatthewSbar/cycle-frontier-item-tracker#17]
One thing that would be cool, I'm not totally sure how the UI would work out, but it's hard to know how many of items I need for current missions & jobs, and how many are needed for future jobs. Especially when you're starting out, the list is *huge*, and sometimes you have to sell stuff to make stash space. This would let people prioritize "I don't want to sell this because I need it right now, but I can sell this because while I need it in the future, I need space in my stash more".

Thanks for making this! It's been very helpful.

**Comment by MatthewSbar** [comment]
Click the star! We're adding a feature that will allow you to select how many steps forward you'd like to consider, so you could keep the list down to the next 3 parts down there for example. I'll be adding the star button for upgrades soon, just been busy.
