### ISSUE TITLE
Kmark Passive Cap

### ISSUE THREAD

**Issue by Beachy66** [MatthewSbar/cycle-frontier-item-tracker#21]
Kmark Passive Cap Tier 4 Level 1 should be 2 Pure Veltecite and 12 Heavy Strider Flesh

**Comment by MatthewSbar** [comment]
My bad, thanks for calling this. Fixed [https://github.com/MatthewSbar/cycle-frontier-item-tracker/commit/b6dcdf71e48fbb09854756390bffa7882f53f147](here) and deployed.
